CREATE DATABASE IF NOT EXISTS blog_post DEFAULT CHARACTER SET utf8;
USE blog_post;
CREATE TABLE IF NOT EXISTS categories
(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name_category VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS tags
(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name_tag VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
login VARCHAR(30) NOT NULL,
password VARCHAR(32) NOT NULL,
nickname VARCHAR(40) NOT NULL,
email VARCHAR(40) UNIQUE NOT NULL
);




